using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "Parameter documentation is visible to end users in Frends and needs to be written in certain way.", Scope = "namespaceanddescendants", Target = "Frends.LinkedIn.SearchAdCampaigns")]
[assembly: SuppressMessage("Minor Code Smell", "S101:Types should be named in PascalCase", Justification = "Some class names should be all capitalized.", Scope = "namespaceanddescendants", Target = "Frends.LinkedIn.SearchAdCampaigns")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Internal classes don't need docs.", Scope = "type", Target = "~T:Frends.LinkedIn.SearchAdCampaigns.Extensions")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Internal classes don't need docs.", Scope = "member", Target = "~M:Frends.LinkedIn.SearchAdCampaigns.Definitions.Result.#ctor(System.Object,System.Collections.Generic.Dictionary{System.String,System.String},System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "Internal classes don't need docs.", Scope = "member", Target = "~M:Frends.LinkedIn.SearchAdCampaigns.Definitions.Result.#ctor(System.Object,System.Collections.Generic.Dictionary{System.String,System.String},System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Internal classes don't need docs.", Scope = "member", Target = "~M:Frends.LinkedIn.SearchAdCampaigns.HttpClientFactory.CreateClient(Frends.LinkedIn.SearchAdCampaigns.Definitions.Options)~System.Net.Http.HttpClient")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Internal classes don't need docs.", Scope = "type", Target = "~T:Frends.LinkedIn.SearchAdCampaigns.HttpClientFactory")]
