using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Following Frends documentation guidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts.Definitions")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Following Frends documentation guidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "Following Frends documentation guidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts.Definitions")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Following Frends documentation guidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Following Frends documentation guidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts.Definitions")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Following Frends documentation guidelines")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "Not needed", Scope = "member", Target = "~M:Frends.LinkedIn.SearchAdAccounts.Definitions.Result.#ctor(System.Object,System.Collections.Generic.Dictionary{System.String,System.String},System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "Parameter examples need to be specific", Scope = "namespaceanddescendants", Target = "Frends.LinkedIn.SearchAdAccounts.Definitions")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1503:Braces should not be omitted", Justification = ".Net6 provides new quidelines", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Enumerations need no docs", Scope = "namespaceanddescendants", Target = "~N:Frends.LinkedIn.SearchAdAccounts.Definitions")]
