name: SearchAdAccounts_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.LinkedIn.SearchAdAccounts/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.LinkedIn.SearchAdAccounts
      env_var_name_1: Frends_LinkedIn_AccessToken
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_LINKEDIN_ACCESSTOKEN }}
      